#! /usr/local/bin/perl

package user;

use strict;
use warnings;
use CGI;

warn "sr7: in perl/common/user\n";

use EnsEMBL::Web::Controller;

{

my $controller = EnsEMBL::Web::Controller->new;

$controller->add_connection({ 'register' => 'EnsEMBL::Web::Controller::Command::User::Register' }); 
$controller->add_connection({ 'activate' => 'EnsEMBL::Web::Controller::Command::User::Activate' }); 
$controller->add_connection({ 'account' => 'EnsEMBL::Web::Controller::Command::User::Account' }); 
$controller->add_connection({ 'share_record' => 'EnsEMBL::Web::Controller::Command::User::ShareRecord' }); 
$controller->add_connection({ 'save_favourites' => 'EnsEMBL::Web::Controller::Command::User::SaveFavourites' }); 
$controller->add_connection({ 'reset_favourites' => 'EnsEMBL::Web::Controller::Command::User::ResetFavourites' }); 
$controller->add_connection({ 'reset_password' => 'EnsEMBL::Web::Controller::Command::User::ResetPassword' }); 
$controller->add_connection({ 'remove_invite' => 'EnsEMBL::Web::Controller::Command::User::RemoveInvite' }); 
$controller->add_connection({ 'save_das' => 'EnsEMBL::Web::Controller::Command::User::SaveDas' }); 
$controller->add_connection({ 'annotation' => 'EnsEMBL::Web::Controller::Command::User::SaveAnnotation' }); 

warn "sr7: in perl/common/user, just before dispatch to : $ENV{REQUEST_URI} \n";
if($ENV{REQUEST_URI} =~ /common\/user\/register\?dataview=success;user_id=/){
  #redirect to vega home
  CGI::redirect('/user_register_message.html');

}
else{

  warn "failed to capture $ENV{REQUEST_URI} \n";

$controller->dispatch($ENV{REQUEST_URI});
}


}

1;
