
<table class="ss" cellpadding="4">

<tr>
<th>Species</th>
<th>DNA</th>
<th>cDNA</th>
<th>Peptides</th>
<th>EMBL</th>
<th>GenBank</th>
<th>MySQL</th>
<th>GTF</th>
<th>EMF</th>
</tr>


<tr>
<td><strong><i>Aedes aegypti</i></strong> (yellow fever mosquito)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/aedes_aegypti_47_1a/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/aedes_aegypti_47_1a/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/aedes_aegypti_47_1a/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/aedes_aegypti_47_1a/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/aedes_aegypti_47_1a/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Anopheles gambiae</i></strong> (African malaria mosquito)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/anopheles_gambiae_47_3i/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/anopheles_gambiae_47_3i/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/anopheles_gambiae_47_3i/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/anopheles_gambiae_47_3i/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/anopheles_gambiae_47_3i/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Bos taurus</i></strong> (cattle)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/bos_taurus_47_3d/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/bos_taurus_47_3d/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/bos_taurus_47_3d/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/bos_taurus_47_3d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/bos_taurus_47_3d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Caenorhabditis elegans</i></strong> (nematode)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/caenorhabditis_elegans_47_180/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/caenorhabditis_elegans_47_180/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/caenorhabditis_elegans_47_180/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/caenorhabditis_elegans_47_180/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/caenorhabditis_elegans_47_180/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Canis familiaris</i></strong> (dog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/canis_familiaris_47_2e/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/canis_familiaris_47_2e/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/canis_familiaris_47_2e/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/canis_familiaris_47_2e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/canis_familiaris_47_2e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Cavia porcellus</i></strong> (domestic guinea pig)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/cavia_porcellus_47_1b/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/cavia_porcellus_47_1b/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/cavia_porcellus_47_1b/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/cavia_porcellus_47_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/cavia_porcellus_47_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Ciona intestinalis</i></strong> (Sea squirt Ciona intestinalis)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_intestinalis_47_2g/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_intestinalis_47_2g/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_intestinalis_47_2g/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/ciona_intestinalis_47_2g/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/ciona_intestinalis_47_2g/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Ciona savignyi</i></strong> (Sea squirt Ciona savignyi)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_savignyi_47_2e/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_savignyi_47_2e/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_savignyi_47_2e/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/ciona_savignyi_47_2e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/ciona_savignyi_47_2e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Danio rerio</i></strong> (zebrafish)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/danio_rerio_47_7a/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/danio_rerio_47_7a/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/danio_rerio_47_7a/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/danio_rerio_47_7a/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/danio_rerio_47_7a/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Dasypus novemcinctus</i></strong> (nine-banded armadillo)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/dasypus_novemcinctus_47_1d/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/dasypus_novemcinctus_47_1d/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/dasypus_novemcinctus_47_1d/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/dasypus_novemcinctus_47_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/dasypus_novemcinctus_47_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Drosophila melanogaster</i></strong> (fruit fly)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster_47_43b/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster_47_43b/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster_47_43b/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/drosophila_melanogaster_47_43b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/drosophila_melanogaster_47_43b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Echinops telfairi</i></strong> (small Madagascar hedgehog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/echinops_telfairi_47_1d/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/echinops_telfairi_47_1d/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/echinops_telfairi_47_1d/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/echinops_telfairi_47_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/echinops_telfairi_47_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Erinaceus europaeus</i></strong> (western European hedgehog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/erinaceus_europaeus_47_1b/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/erinaceus_europaeus_47_1b/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/erinaceus_europaeus_47_1b/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/erinaceus_europaeus_47_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/erinaceus_europaeus_47_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Felis catus</i></strong> (cat)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/felis_catus_47_1b/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/felis_catus_47_1b/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/felis_catus_47_1b/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/felis_catus_47_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/felis_catus_47_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Gallus gallus</i></strong> (chicken)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/gallus_gallus_47_2e/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/gallus_gallus_47_2e/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/gallus_gallus_47_2e/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/gallus_gallus_47_2e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/gallus_gallus_47_2e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Gasterosteus aculeatus</i></strong> (three spined stickleback)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/gasterosteus_aculeatus_47_1d/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/gasterosteus_aculeatus_47_1d/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/gasterosteus_aculeatus_47_1d/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/gasterosteus_aculeatus_47_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/gasterosteus_aculeatus_47_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Homo sapiens</i></strong> (human)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/homo_sapiens_47_36i/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/homo_sapiens_47_36i/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/homo_sapiens_47_36i/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/homo_sapiens_47_36i/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/homo_sapiens_47_36i/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_emf/homo_sapiens_variation_47_36i/">FTP</a></td>
</tr>
	    
<tr>
<td><strong><i>Loxodonta africana</i></strong> (African savanna elephant)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/loxodonta_africana_47_1c/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/loxodonta_africana_47_1c/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/loxodonta_africana_47_1c/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/loxodonta_africana_47_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/loxodonta_africana_47_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Macaca mulatta</i></strong> (rhesus monkey)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/macaca_mulatta_47_10f/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/macaca_mulatta_47_10f/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/macaca_mulatta_47_10f/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/macaca_mulatta_47_10f/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/macaca_mulatta_47_10f/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Monodelphis domestica</i></strong> (gray short-tailed opossum)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/monodelphis_domestica_47_5b/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/monodelphis_domestica_47_5b/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/monodelphis_domestica_47_5b/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/monodelphis_domestica_47_5b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/monodelphis_domestica_47_5b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Mus musculus</i></strong> (house mouse)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_47_37/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_47_37/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_47_37/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/mus_musculus_47_37/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/mus_musculus_47_37/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_emf/mus_musculus_variation_47_37/">FTP</a></td>
</tr>
	    
<tr>
<td><strong><i>Myotis lucifugus</i></strong> (little brown bat)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/myotis_lucifugus_47_1c/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/myotis_lucifugus_47_1c/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/myotis_lucifugus_47_1c/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/myotis_lucifugus_47_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/myotis_lucifugus_47_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Ornithorhynchus anatinus</i></strong> (platypus)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ornithorhynchus_anatinus_47_1d/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ornithorhynchus_anatinus_47_1d/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ornithorhynchus_anatinus_47_1d/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/ornithorhynchus_anatinus_47_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/ornithorhynchus_anatinus_47_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Oryctolagus cuniculus</i></strong> (rabbit)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/oryctolagus_cuniculus_47_1d/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/oryctolagus_cuniculus_47_1d/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/oryctolagus_cuniculus_47_1d/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/oryctolagus_cuniculus_47_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/oryctolagus_cuniculus_47_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Oryzias latipes</i></strong> (Japanese medaka)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/oryzias_latipes_47_1c/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/oryzias_latipes_47_1c/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/oryzias_latipes_47_1c/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/oryzias_latipes_47_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/oryzias_latipes_47_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Otolemur garnettii</i></strong> (small-eared galago)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/otolemur_garnettii_47_1a/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/otolemur_garnettii_47_1a/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/otolemur_garnettii_47_1a/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/otolemur_garnettii_47_1a/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/otolemur_garnettii_47_1a/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Pan troglodytes</i></strong> (chimpanzee)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/pan_troglodytes_47_21f/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/pan_troglodytes_47_21f/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/pan_troglodytes_47_21f/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/pan_troglodytes_47_21f/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/pan_troglodytes_47_21f/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Rattus norvegicus</i></strong> (Norway rat)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/rattus_norvegicus_47_34q/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/rattus_norvegicus_47_34q/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/rattus_norvegicus_47_34q/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/rattus_norvegicus_47_34q/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/rattus_norvegicus_47_34q/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_emf/rattus_norvegicus_variation_47_34q/">FTP</a></td>
</tr>
	    
<tr>
<td><strong><i>Saccharomyces cerevisiae</i></strong> (baker's yeast)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/saccharomyces_cerevisiae_47_1g/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/saccharomyces_cerevisiae_47_1g/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/saccharomyces_cerevisiae_47_1g/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/saccharomyces_cerevisiae_47_1g/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/saccharomyces_cerevisiae_47_1g/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Sorex araneus</i></strong> (European shrew)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/sorex_araneus_47_1a/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/sorex_araneus_47_1a/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/sorex_araneus_47_1a/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/sorex_araneus_47_1a/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/sorex_araneus_47_1a/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Spermophilus tridecemlineatus</i></strong> (thirteen-lined ground squirrel)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/spermophilus_tridecemlineatus_47_1c/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/spermophilus_tridecemlineatus_47_1c/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/spermophilus_tridecemlineatus_47_1c/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/spermophilus_tridecemlineatus_47_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/spermophilus_tridecemlineatus_47_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Takifugu rubripes</i></strong> (torafugu)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/takifugu_rubripes_47_4g/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/takifugu_rubripes_47_4g/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/takifugu_rubripes_47_4g/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/takifugu_rubripes_47_4g/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/takifugu_rubripes_47_4g/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Tetraodon nigroviridis</i></strong> (Fresh water pufferfish)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/tetraodon_nigroviridis_47_1i/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/tetraodon_nigroviridis_47_1i/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/tetraodon_nigroviridis_47_1i/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/tetraodon_nigroviridis_47_1i/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/tetraodon_nigroviridis_47_1i/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Tupaia belangeri</i></strong> (northern tree shrew)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/tupaia_belangeri_47_1b/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/tupaia_belangeri_47_1b/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/tupaia_belangeri_47_1b/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/tupaia_belangeri_47_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/tupaia_belangeri_47_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Xenopus tropicalis</i></strong> (western clawed frog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/xenopus_tropicalis_47_41g/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/xenopus_tropicalis_47_41g/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/xenopus_tropicalis_47_41g/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/xenopus_tropicalis_47_41g/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/xenopus_tropicalis_47_41g/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong>Multi-species</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td>-</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_emf/">FTP</a></td>
</tr>
<tr>
<td><strong>Ensembl Mart</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td>-</td>
<td>-</td>
</tr>
      </table>